-- liquibase formatted sql

-- changeset yuzu:1

create table ads (
id int8 generated by default as identity,
description varchar(255) not null,
price int4 not null,
title varchar(255) not null,
author_id int8,
image_id int8,
primary key (id))